### ISSUE TITLE
XBee not being found on comport in Linux

### ISSUE THREAD

**Issue by ryanjmarcotte** [utdrobotchess/chess-game#7] opened 2015-04-09 20:49 UTC

**Comment by ohasangit** [comment] 2015-07-06 18:40
After testing on a Linux machine, I have confirmed that this does work. I tried it on Ubuntu 14.04, so I'm not sure about other flavors of Linux, or of other machines in general. I believe it didn't work for Ryan on his Lenovo Thinkpad running Ubuntu. However, I'm closing this issue since I believe enough of the source code has changed since he tried it.

**Closed as completed by ohasangit** 2015-07-06 18:40 UTC
